Repository Grogro21/tp-git-a-deux, pull requests merged in 2024-01, with the labels that each got.

#3 Merge test
  README.md
Labels: documentation

#4 correction faute
  README.md
Labels: documentation

#21 release 1.0.0
  src/.vs/ProjectEvaluation/src.metadata.v5.1
  src/.vs/ProjectEvaluation/src.projects.v5.1
  src/.vs/src/DesignTimeBuild/.dtbcache.v2
  src/.vs/src/FileContentIndex/19eb35b8-1e2e-447f-a678-818b9c96fe0f.vsidx
  src/.vs/src/FileContentIndex/4e1c081e-4ad1-446e-aa75-bdc887883536.vsidx
  src/.vs/src/FileContentIndex/50bacff2-bbaf-4edf-98b0-1871951026d0.vsidx
  src/.vs/src/FileContentIndex/e96d947f-eb2f-46b5-95ed-d3a0344a01ac.vsidx
  src/.vs/src/FileContentIndex/ee66fe7f-528a-4d72-9d3e-0530bbf48af7.vsidx
  src/.vs/src/v17/.suo
  src/PeopleContainer.cs
  src/Person.cs
  src/Program.cs
  src/bin/Debug/net6.0/savefile.json
  src/bin/Debug/net6.0/savefile2.json
  src/bin/Debug/net6.0/src.dll
  src/bin/Debug/net6.0/src.pdb
  src/obj/Debug/net6.0/ref/src.dll
  src/obj/Debug/net6.0/refint/src.dll
  src/obj/Debug/net6.0/src.dll
  src/obj/Debug/net6.0/src.pdb
Labels: v1.0

#22 release
  src/.vs/ProjectEvaluation/src.metadata.v5.1
  src/.vs/ProjectEvaluation/src.projects.v5.1
  src/.vs/src/DesignTimeBuild/.dtbcache.v2
  src/.vs/src/FileContentIndex/19eb35b8-1e2e-447f-a678-818b9c96fe0f.vsidx
  src/.vs/src/FileContentIndex/4a7024e5-c3cb-461e-978d-6020b08e7298.vsidx
  src/.vs/src/FileContentIndex/50bacff2-bbaf-4edf-98b0-1871951026d0.vsidx
  src/.vs/src/FileContentIndex/6d936ac6-2ea6-40c4-8f3f-937460724da4.vsidx
  src/.vs/src/FileContentIndex/787799ce-12c6-4def-8bbd-d8e66f42cfe5.vsidx
  src/.vs/src/FileContentIndex/addcf4ec-2304-40b5-887b-c64da4fe00e0.vsidx
  src/.vs/src/FileContentIndex/e96d947f-eb2f-46b5-95ed-d3a0344a01ac.vsidx
  src/.vs/src/FileContentIndex/ee66fe7f-528a-4d72-9d3e-0530bbf48af7.vsidx
  src/.vs/src/v17/.futdcache.v2
  src/.vs/src/v17/.suo
  src/Program.cs
  src/bin/Debug/net6.0/savefile.json
  src/bin/Debug/net6.0/src.dll
  src/bin/Debug/net6.0/src.pdb
  src/bin/Release/net6.0/savefile.json
  src/bin/Release/net6.0/src.deps.json
  src/bin/Release/net6.0/src.dll
  src/bin/Release/net6.0/src.exe
  src/bin/Release/net6.0/src.pdb
  src/bin/Release/net6.0/src.runtimeconfig.json
  src/obj/Debug/net6.0/src.dll
  src/obj/Debug/net6.0/src.pdb
  src/obj/Release/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  src/obj/Release/net6.0/apphost.exe
  src/obj/Release/net6.0/ref/src.dll
  src/obj/Release/net6.0/refint/src.dll
  src/obj/Release/net6.0/src.AssemblyInfo.cs
  src/obj/Release/net6.0/src.AssemblyInfoInputs.cache
  src/obj/Release/net6.0/src.GeneratedMSBuildEditorConfig.editorconfig
  src/obj/Release/net6.0/src.GlobalUsings.g.cs
  src/obj/Release/net6.0/src.assets.cache
  src/obj/Release/net6.0/src.csproj.AssemblyReference.cache
  src/obj/Release/net6.0/src.csproj.BuildWithSkipAnalyzers
  src/obj/Release/net6.0/src.csproj.CoreCompileInputs.cache
  src/obj/Release/net6.0/src.csproj.FileListAbsolute.txt
  src/obj/Release/net6.0/src.dll
  src/obj/Release/net6.0/src.genruntimeconfig.cache
  src/obj/Release/net6.0/src.pdb
  src/src.sln
Labels: release, v1.0.1

#23 Update README.md
  README.md
Labels: documentation
